### PR TITLE
Changed the name & the version

### PR DESCRIPTION
**Pull request by roii31-game**
Changed the name on package.json
Sorry about the randomness, but this is my first PR. I'm learning :)

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
what is hellowworld?🙂 please read this issue carefully #85

**Comment by devvsakib** [comment]
In this #85 issue I have described how to rename project file, you can do it💪🏻💪🏻 waiting for your pr

**Comment by devvsakib** [comment]
and comment here, so I can assign you to this issue #85 . good luck with first opensource

**Comment by devvsakib** [comment]
if you need guide, let me know

**Comment by devvsakib** [comment]
@roii31-game are you there?

**Comment by roii31-game** [comment]
Hey i'm here. I posted a new commit. Let me know.

**Pull request closed without merging**
