### PR TITLE
Adding transition delay to filter button

### PR DESCRIPTION
**Pull request by hussain-shariff**
added 600 sec transition delay

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
I actually didn't mean that. I mean when someone clicks the button it will appear slowly, like from top to bottom.

**Comment by hussain-shariff** [comment]
> I actually didn't mean that. I mean when someone clicks the button it will appear slowly, like from top to bottom.

got it .

**Comment by devvsakib** [comment]
🚀🚀 @hussain-shariff

**Comment by hussain-shariff** [comment]
Hey @devvsakib you can look at it now.
the menu now will transition from left to right .
It looks better than what you said from top to bottom

**Comment by devvsakib** [comment]
cz you didnt pull latest code before pull request, its on me, i will solve the conflict.

well done @hussain-shariff . love it

**Review by devvsakib — APPROVED** [review]
awesome stuff hussain

**Pull request merged**
