### PR TITLE
removed extra clear button

### PR DESCRIPTION
**Pull request by hussain-shariff**
Screenshot (179)

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
I can't see any button here, did you just remove the button?

image

**Comment by hussain-shariff** [comment]
> I can't see any button here, did you just remove the button?
> 
> image

@devvsakib  it will be visible when you hover on the search bar

**Comment by devvsakib** [comment]
?? @hussain-shariff 
image

**Comment by devvsakib** [comment]
please check the preview to confirm that it's working, I can't see any close button when I hover, even if I type something its not visible @hussain-shariff

**Comment by devvsakib** [comment]
Okkkyyyy. I checked on the chrome browser, it's working fine, but not working in firefox. can you figure out what happens here?
also when the search input is empty, the scrollbar shows, but when we type something scrollbar disappears. 
image
image

maybe if we change the input type search to text, it may help. what do you think?

**Comment by hussain-shariff** [comment]
@devvsakib

**Review by devvsakib — APPROVED** [review]

**Comment by devvsakib** [comment]
@hussain-shariff  amazing work

**Pull request merged**
