### PR TITLE
Add Contribution Page & Contribution Section in (README)

### PR DESCRIPTION
**Pull request by MohamedAlDeep**
#82 added contribution page
#77 added contribution section in readme

### CODE REVIEW

**Comment by MohamedAlDeep** [comment]
@devvsakib

**Review by devvsakib — APPROVED** [review]
Amazing

**Comment by devvsakib** [comment]
hi, readme file has a conflict. please check mark **Allow maintainer to edit** option

**Review by devvsakib — CHANGES_REQUESTED** [review]
@MohamedAlDeep ?

**Comment by MohamedAlDeep** [comment]
Hi, alr i will check it

**Comment by MohamedAlDeep** [comment]
Done @devvsakib

**Comment by devvsakib** [comment]
still conflict
image

**Comment by MohamedAlDeep** [comment]
@devvsakib

**Review by devvsakib — APPROVED** [review]
very nice pr.
your branch was protected that's why I want able to edit or resolve conflict

**Pull request merged**
