### PR TITLE
Added new error & Removed additional data in Contibutors.json

### PR DESCRIPTION
**Pull request by MohamedAlDeep**
@devvsakib Hey remember the twitter problem, now i know how we can get the twitter it is in the data of the user himself
so maybe we can fetch the contributors api_url from the https://api.github.com/repos/devvsakib/github-error-solve/contributors
### Image
image

and use it to fetch the twiter data from the user api 
https://api.github.com/users/devvsakib
### Image
image

### CODE REVIEW

**Comment by MohamedAlDeep** [comment]
So

**Comment by MohamedAlDeep** [comment]
I think what we will have to do is 
1. get the `"url"`
2. use it to  get the `"twitter_username"`

**Comment by MohamedAlDeep** [comment]
so the actual complicated part for me is to get the twitter username from the user api

**Comment by MohamedAlDeep** [comment]
Waiting for Review 
Pending #95

**Review by devvsakib — APPROVED** [review]

**Pull request merged**
