### PR TITLE
fixed title (overflow & size)

### PR DESCRIPTION
**Pull request by MohamedAlDeep**
Hello,
So i fixed the overflow issue No: #52,
so you see that i added id for the card div (it was to change some css for the div but it didnt work ) so you can delete it if you want. 
----
In css i added 
```css
h3{
  max-width:  100%;
  overflow: break-word;
}
```
which break the words when overflowing and that is it

### CODE REVIEW

**Comment by MohamedAlDeep** [comment]
image
image

**Review by devvsakib — APPROVED** [review]
Amazing stuff. 
are you able to change the title size lg to sm? bcz title size is pretty big
line: 48

**Comment by MohamedAlDeep** [comment]
Sure

**Comment by MohamedAlDeep** [comment]
@devvsakib 
Hi i did it but i dont know which size in px 
16px
image

14px 
image
10px

**Comment by MohamedAlDeep** [comment]
@devvsakib 
Hi i did it but i dont know which size in px 
16px
image

14px 
image
10px

**Comment by MohamedAlDeep** [comment]
@devvsakib 
Hi i did it but i dont know which size in px 
16px
image

14px 
image
10px

**Review by devvsakib — APPROVED** [review]

**Pull request merged**
